### ISSUE TITLE
doctest failure with filemanip and Glob in scope

### ISSUE THREAD

**Issue by bergmark** [twanvl/multiset#7]
This is a limitation of doctest and won't occur unless both these packages are in scope. I think it can be resolved by using PackageImports - assuming it matters to you. I'll disable this test-suite on stackage at least for now.

```
/tmp/stackage-build1/multiset-0.3.1/test/Main.hs:3:8:
    Ambiguous module name ‘System.FilePath.Glob’:
      it was found in multiple packages:
      filemanip-0.3.6.3@filem_AFSulF8Y70TAA5R8pjLEdB Glob-0.7.5@Glob_J8eYhnaKSeW8dehUANn0F1
```

**Comment by rcook** [comment]
@bergmark: How are you building the module? Is there a guide somewhere describing how packages are built for Stackage so I can reproduce this failure? I'd like to fix this and verify that the fix works when run as part of your process.

**Comment by rcook** [comment]
I'll investigate.

**Comment by rcook** [comment]
@bergmark : This should do the trick. This was tested by building using plain ol' `cabal build && cabal test` instead of using the equivalent `stack` commands. I made sure that both `filemanip` and `Glob` were present on my system in order to verify that the `PackageImports` extension eliminates the ambiguity. @twanvl : Sorry for introducing this build failure. This will, presumably, require another bump of the package version number on Hackage.

**Comment by bergmark** [comment]
Thanks! It's hard to secure yourself against problems like this since any two packages could export the same module name...
